services:
  nestjs_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src