version: '3.8'

services:
  api:
    container_name: "api_${NODE_ENV}"
    image: "api_${NODE_ENV}"
    environment:
      - NODE_ENV=${NODE_ENV}
    build:
      context: ./
      # target: ${NODE_ENV}
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - 3000:3000
    networks:
      - app-network
    volumes:
      - ./app:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped # se usa porque en caso de que el contenedor se detenga, se reinicie automaticamente

networks:
  app-network:
    driver: bridge
